<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>preview</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<EnablePreviewFeatures>true</EnablePreviewFeatures>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>

	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DefineConstants>$(DefineConstants);MATRIX_LEFTHANDED_COORDINATE_SYSTEM;MATRIX_PREMULTIPLIED_CONVENTION</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DefineConstants>$(DefineConstants);MATRIX_LEFTHANDED_COORDINATE_SYSTEM;MATRIX_PREMULTIPLIED_CONVENTION</DefineConstants>
	</PropertyGroup>

</Project>
